// Generated by archstrict init from archstrict.config.ts's own
// declaredModules. Do not edit this file directly: after adding, removing,
// or renaming a declaredModules entry, run archstrict init again to
// regenerate this union to match.
export type ModuleName = "agent-reporter.ts" | "build-lines.ts" | "cli.ts" | "convert.ts" | "gate.ts" | "index.ts";

// configPath is added by the loader, not written here - a config file
// cannot know its own path.
export type Config = {
  // The schema this config was written for. 1 is the only
  // value archstrict reads. Omit it and the loader treats the file as
  // schema 1.
  schemaVersion?: 1;
  surface?: string | readonly string[];
  deprecated?: readonly {
    from: ModuleName;
    to: ModuleName;
    count: number;
    because: string;
  }[];
  // Module names whose todo entries may only shrink, never gain a new one.
  // check reports any existing entry for one of these modules as a
  // violation in its own right.
  strict?: readonly ModuleName[];
  // A specific known cycle (naming any two modules in it, in either
  // order) exempted from rule 2 - an entry naming a pair no longer in any
  // real cycle is itself flagged (stale-cycle-exception).
  ignoredCycles?: readonly (readonly [string, string])[];
  // An analysis boundary narrower than the whole project - not yet read
  // by any rule or verb (declared here for forward compatibility; wiring
  // it in is separate, later work).
  scope?: string;
  // Glob patterns kept out of analysis entirely - not a member of any
  // module, not a source of edges, not a target either. init writes one
  // default: this project's own root-level files (archstrict.config.ts,
  // archstrict.types.ts) are never module content.
  exclude?: readonly string[];
  // glob -> tags, most-specific-glob-wins. Independent of declaredModules
  // below - tags classify any file; declaredModules says which files form
  // an enforced module boundary.
  classify?: readonly { glob: string; tags: readonly string[] }[];
  // Ambient tagging by directory-name segment: the nearest path segment
  // matching one of `names`, walking from the file outward, becomes
  // `${tagNamespace}:${name}`. Independent of `classify` above - a file
  // can carry tags from both mechanisms at once.
  classifyByDirectoryName?: {
    tagNamespace: string;
    names: readonly string[];
  };
  // Declared modules - the source of truth for module boundaries.
  // `surface` may itself be a glob (a module's public surface can be
  // more than one file).
  declaredModules: readonly {
    name: ModuleName;
    glob: string;
    // A single glob, or several - a real package can publish more than
    // one real, differently-shaped public entry point at once. Optional:
    // when absent, a real package.json's own exports map at this
    // module's own root is derived back to source instead, falling back
    // to this project's own top-level surface default otherwise.
    surface?: string | readonly string[];
    // Rule 1's own "friend" exception: `file` (relative to this module,
    // may itself be a glob) is public to exactly the importers `from`
    // (a project-relative glob) matches, private to everyone else -
    // unlike `surface`, which is public to every importer equally.
    friends?: readonly { file: string; from: string; because: string }[];
  }[];
  // A directory that must hold no code at all (archspec's own
  // "empty component" idea) - a violation is any file matching the glob.
  mustBeEmpty?: readonly { glob: string; because: string }[];
  // The constraint engine: allowDeny/order/point rules over classify
  // tags, generalizing the fixed module vocabulary above. `allowDeny`'s
  // own `exceptions`: a from/to glob or tag-predicate pair that overrides
  // that rule either way for one specific edge - `point` has no
  // exceptions of its own, its from/to predicates already being as
  // explicit as a rule gets.
  edges?: {
    allowDeny?: readonly {
      source: string;
      targetNamespace: string;
      allow?: readonly string[];
      deny?: readonly string[];
      exceptions?: readonly { from: string; to: string; because: string }[];
      edgeType?: "value" | "type" | "both";
      importForm?: "static" | "dynamic" | "both";
      because: string;
    }[];
    order?: readonly {
      tagNamespace: string;
      within?: string;
      sequence: Record<string, readonly string[]>;
      direction: "downward-only";
      edgeType?: "value" | "type" | "both";
      importForm?: "static" | "dynamic" | "both";
      because: string;
    }[];
    point?: readonly {
      from: string | { tags: readonly string[]; exclude?: { tags: readonly string[] } };
      to: string | { tags: readonly string[] };
      edgeType?: "value" | "type" | "both";
      importForm?: "static" | "dynamic" | "both";
      because: string;
    }[];
  };
  because: string;
};
